"""VLM cross-check for labels.jsonl ownership judgements.

Multiple VLM judges independently predict the ownership label (MINE / PERSON_k /
SHARED / AMBIGUOUS) from the 3 sparse frames alone (frame t always gets the
verified reference bbox; t-1/t-2 get their own genuinely-tracked box when
--sam2-track produced one, otherwise shown unboxed rather than reusing a
stale or unrelated fallback box) — no narration, no object visual
description (that's generated by our own captioning stage and would leak the
pipeline's own reasoning), and no access to the pipeline's own zone/relation/
object-type/temporal evidence, so the judge's reasoning is genuinely
independent. Each judge answers with a
label plus one sentence per remaining evidence aspect (object_type_evidence,
zone_evidence, relation_graph_evidence, context_change_evidence) — the same
field names used in scene_records.jsonl's auto_key_evidence, so a judge's
reasoning and the pipeline's own can be compared side-by-side per aspect.
Each judge's answer is compared to ``auto_ground_truth`` and recorded.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import tempfile
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol

def _iter_jsonl(path: Path) -> Any:
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                try:
                    yield json.loads(line)
                except json.JSONDecodeError:
                    pass

VALID_LABELS = {"MINE", "PERSON_k", "SHARED", "AMBIGUOUS"}
# PERSON_k is the only mixed-case label — comparing it after `.upper()`ing an
# extracted candidate (or searching within an upper-cased text blob) silently
# never matches it, since the "k" only appears lowercase. Canonicalize through
# this upper-keyed lookup instead of case-folding VALID_LABELS members directly.
_LABEL_LOOKUP = {label.upper(): label for label in VALID_LABELS}

# "_k" in PERSON_k is a template placeholder — our schema never tracks *which*
# person, just "not the wearer" — but models reasonably read it as "fill in
# the index" and answer PERSON_1 / PERSON_2 / etc. instead of the literal
# string. Treat any such indexed variant as PERSON_k.
_PERSON_VARIANT_RE = re.compile(r"\bPERSON[_ ]?\d+\b")


def _canonicalize_label(raw_label: str) -> str | None:
    candidate = raw_label.strip().upper()
    exact = _LABEL_LOOKUP.get(candidate)
    if exact is not None:
        return exact
    if _PERSON_VARIANT_RE.fullmatch(candidate):
        return "PERSON_k"
    return None

# ---------------------------------------------------------------------------
# Prompt helpers
# ---------------------------------------------------------------------------

_SYSTEM = (
    "You are an expert annotator for egocentric video understanding. "
    "You decide who OWNS or primarily uses a highlighted target object "
    "visible in first-person (ego-camera) footage."
)

_LABEL_DEFS = """\
Label definitions:
  MINE      – the camera wearer (ego) primarily owns / uses this object
  PERSON_k  – another person in the scene primarily owns / uses this object
  SHARED    – ownership is genuinely shared between multiple people
  AMBIGUOUS – impossible to determine from the available evidence
"""


_EVIDENCE_ASPECTS = """\
Reason through these aspects (skip any that aren't determinable from the
frames — don't guess), and answer each in one concise sentence:
  1. Object type          – is this an inherently shared/communal item (e.g. serving-ware,
     condiments) regardless of who's touching it, or a personal-use item (e.g. phone, wallet)?
  2. Zone                 – where it sits relative to the camera wearer vs. other visible people
     (in the wearer's own space, in someone else's space, or on shared/neutral ground)
  3. Relation              – whose hand (if anyone's) is touching or holding it right now
  4. Temporal context      – does its position or holder change across t-2 → t-1 → t?
"""

_EVIDENCE_FIELDS = (
    "object_type_evidence",
    "zone_evidence",
    "relation_graph_evidence",
    "context_change_evidence",
)


def _build_prompt(record: dict[str, Any]) -> str:
    noun = str((record.get("object") or {}).get("label") or record.get("nouns", ["object"])[0])

    lines = [
        f"Target object: {noun}",
        "",
        _LABEL_DEFS,
        "You are shown three frames from the video. The target object is boxed in red",
        "wherever its position is reliably known — always in frame t; in t-2/t-1 too",
        "when available, otherwise those are shown without a box (don't assume the",
        "object is absent just because it isn't boxed there):",
        "  • frame t-2  (2 seconds before the action)",
        "  • frame t-1  (1 second before the action)",
        "  • frame t    (the action moment — always boxed)",
        "",
        _EVIDENCE_ASPECTS,
        "Respond ONLY with valid JSON (no markdown fences), one sentence per field. "
        "If an aspect isn't determinable from the frames, omit that field entirely — "
        "do not guess or fill it with a placeholder:",
        '{"label": "<MINE|PERSON_k|SHARED|AMBIGUOUS>", '
        '"object_type_evidence": "<aspect 1, or omit>", '
        '"zone_evidence": "<aspect 2, or omit>", '
        '"relation_graph_evidence": "<aspect 3, or omit>", '
        '"context_change_evidence": "<aspect 4, or omit>"}',
    ]
    return "\n".join(l for l in lines if l is not None)


# ---------------------------------------------------------------------------
# Protocol
# ---------------------------------------------------------------------------

class OwnershipJudge(Protocol):
    model_id: str

    def judge(
        self,
        frame_paths: list[Path],  # [t-2, t-1, t] — bbox always on t, on t-1/t-2 only if genuinely tracked
        record: dict[str, Any],
    ) -> dict[str, Any]:
        """Return {"label", "object_type_evidence", "zone_evidence",
        "relation_graph_evidence", "context_change_evidence"}."""


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _parse_label_response(raw: str) -> dict[str, Any]:
    """Extract the label plus each per-aspect evidence field, one by one, from
    a VLM text response — mirroring scene_records.jsonl's auto_key_evidence
    field names so the two are directly comparable."""
    raw = raw.strip()
    # Strip markdown fences if present.
    raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.MULTILINE)
    raw = re.sub(r"\s*```$", "", raw, flags=re.MULTILINE)
    try:
        data = json.loads(raw)
        label = _canonicalize_label(str(data.get("label", "")))
        if label is None:
            label = _extract_label_from_text(raw)
        result: dict[str, Any] = {"label": label}
        for field_name in _EVIDENCE_FIELDS:
            value = data.get(field_name)
            result[field_name] = str(value).strip() if value else ""
        return result
    except (json.JSONDecodeError, ValueError):
        label = _extract_label_from_text(raw)
        result = {"label": label, **{field_name: "" for field_name in _EVIDENCE_FIELDS}}
        result["raw_response"] = raw[:200]
        return result


def _extract_label_from_text(text: str) -> str:
    upper_text = text.upper()
    for candidate_upper, candidate in _LABEL_LOOKUP.items():
        if candidate_upper in upper_text:
            return candidate
    if _PERSON_VARIANT_RE.search(upper_text):
        return "PERSON_k"
    return "UNKNOWN"


def _draw_bbox_on_frame(src: Path, dst: Path, bbox: dict[str, Any]) -> None:
    """Copy src to dst and draw normalized bbox in red."""
    try:
        from PIL import Image, ImageDraw
        with Image.open(src).convert("RGB") as img:
            w, h = img.size
            draw = ImageDraw.Draw(img)
            x1 = int(bbox.get("x_min", 0) * w)
            y1 = int(bbox.get("y_min", 0) * h)
            x2 = int(bbox.get("x_max", 1) * w)
            y2 = int(bbox.get("y_max", 1) * h)
            lw = max(3, round(min(w, h) * 0.006))
            for off in range(lw):
                draw.rectangle((x1 - off, y1 - off, x2 + off, y2 + off), outline=(255, 50, 50))
            img.save(dst, quality=92)
    except Exception:
        shutil.copy2(src, dst)


# ---------------------------------------------------------------------------
# Qwen VL judge
# ---------------------------------------------------------------------------

@dataclass
class QwenOwnershipJudgeConfig:
    model_id: str = "Qwen/Qwen2.5-VL-7B-Instruct"
    device: str = "auto"
    dtype: str = "auto"
    max_new_tokens: int = 256
    trust_remote_code: bool = True


class QwenOwnershipJudge:
    def __init__(self, cfg: QwenOwnershipJudgeConfig | None = None):
        self.cfg = cfg or QwenOwnershipJudgeConfig()
        self.model_id = self.cfg.model_id
        self._model: Any = None
        self._processor: Any = None

    def _load(self) -> tuple[Any, Any]:
        if self._model is None:
            import torch
            from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration

            dtype_map = {"float16": torch.float16, "bfloat16": torch.bfloat16, "float32": torch.float32}
            dtype = dtype_map.get(self.cfg.dtype, "auto") if self.cfg.dtype != "auto" else "auto"
            self._model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
                self.cfg.model_id,
                torch_dtype=dtype,
                device_map=self.cfg.device,
                trust_remote_code=self.cfg.trust_remote_code,
            )
            self._model.eval()
            self._processor = AutoProcessor.from_pretrained(
                self.cfg.model_id,
                trust_remote_code=self.cfg.trust_remote_code,
            )
        return self._processor, self._model

    def judge(self, frame_paths: list[Path], record: dict[str, Any]) -> dict[str, Any]:
        processor, model = self._load()

        content: list[dict] = []
        for fp in frame_paths:
            if fp.exists():
                content.append({"type": "image", "image": str(fp)})
        content.append({"type": "text", "text": _build_prompt(record)})

        messages = [{"role": "user", "content": content}]
        text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

        from qwen_vl_utils import process_vision_info
        image_inputs, video_inputs = process_vision_info(messages)
        inputs = processor(text=[text], images=image_inputs, videos=video_inputs,
                           padding=True, return_tensors="pt")

        try:
            device = next(model.parameters()).device
            inputs = inputs.to(device)
        except Exception:
            pass

        import torch
        with torch.inference_mode():
            output_ids = model.generate(
                **inputs,
                max_new_tokens=self.cfg.max_new_tokens,
                do_sample=False,
            )
        trimmed = output_ids[:, inputs["input_ids"].shape[1]:]
        raw = processor.batch_decode(trimmed, skip_special_tokens=True)[0]
        return _parse_label_response(raw)


# ---------------------------------------------------------------------------
# Anthropic (Claude) judge
# ---------------------------------------------------------------------------

@dataclass
class AnthropicOwnershipJudgeConfig:
    model_id: str = "claude-sonnet-4-6"
    max_tokens: int = 512
    api_key: str | None = None  # falls back to ANTHROPIC_API_KEY env var


class AnthropicOwnershipJudge:
    def __init__(self, cfg: AnthropicOwnershipJudgeConfig | None = None):
        self.cfg = cfg or AnthropicOwnershipJudgeConfig()
        self.model_id = self.cfg.model_id
        self._client: Any = None

    def _load(self) -> Any:
        if self._client is None:
            import anthropic
            self._client = anthropic.Anthropic(
                **({"api_key": self.cfg.api_key} if self.cfg.api_key else {})
            )
        return self._client

    def judge(self, frame_paths: list[Path], record: dict[str, Any]) -> dict[str, Any]:
        import base64
        client = self._load()

        content: list[dict] = []
        for fp in frame_paths:
            if fp.exists():
                data = base64.standard_b64encode(fp.read_bytes()).decode()
                content.append({
                    "type": "image",
                    "source": {"type": "base64", "media_type": "image/jpeg", "data": data},
                })
        content.append({"type": "text", "text": _build_prompt(record)})

        response = client.messages.create(
            model=self.cfg.model_id,
            max_tokens=self.cfg.max_tokens,
            system=_SYSTEM,
            messages=[{"role": "user", "content": content}],
        )
        raw = response.content[0].text
        return _parse_label_response(raw)


# ---------------------------------------------------------------------------
# OpenAI judge
# ---------------------------------------------------------------------------

@dataclass
class OpenAIOwnershipJudgeConfig:
    model_id: str = "gpt-4o"
    max_tokens: int = 512
    api_key: str | None = None


class OpenAIOwnershipJudge:
    def __init__(self, cfg: OpenAIOwnershipJudgeConfig | None = None):
        self.cfg = cfg or OpenAIOwnershipJudgeConfig()
        self.model_id = self.cfg.model_id
        self._client: Any = None

    def _load(self) -> Any:
        if self._client is None:
            from openai import OpenAI
            self._client = OpenAI(
                **({"api_key": self.cfg.api_key} if self.cfg.api_key else {})
            )
        return self._client

    def judge(self, frame_paths: list[Path], record: dict[str, Any]) -> dict[str, Any]:
        import base64
        client = self._load()

        content: list[dict] = []
        for fp in frame_paths:
            if fp.exists():
                data = base64.standard_b64encode(fp.read_bytes()).decode()
                content.append({
                    "type": "image_url",
                    "image_url": {"url": f"data:image/jpeg;base64,{data}", "detail": "high"},
                })
        content.append({"type": "text", "text": _build_prompt(record)})

        response = client.chat.completions.create(
            model=self.cfg.model_id,
            max_tokens=self.cfg.max_tokens,
            messages=[
                {"role": "system", "content": _SYSTEM},
                {"role": "user", "content": content},
            ],
        )
        raw = response.choices[0].message.content or ""
        return _parse_label_response(raw)


# ---------------------------------------------------------------------------
# Gemini judge
# ---------------------------------------------------------------------------

@dataclass
class GeminiOwnershipJudgeConfig:
    model_id: str = "gemini-2.0-flash"
    max_tokens: int = 512
    api_key: str | None = None


class GeminiOwnershipJudge:
    def __init__(self, cfg: GeminiOwnershipJudgeConfig | None = None):
        self.cfg = cfg or GeminiOwnershipJudgeConfig()
        self.model_id = self.cfg.model_id
        self._client: Any = None

    def _load(self) -> Any:
        if self._client is None:
            import google.generativeai as genai
            if self.cfg.api_key:
                genai.configure(api_key=self.cfg.api_key)
            self._client = genai.GenerativeModel(
                model_name=self.cfg.model_id,
                system_instruction=_SYSTEM,
                generation_config={"max_output_tokens": self.cfg.max_tokens},
            )
        return self._client

    def judge(self, frame_paths: list[Path], record: dict[str, Any]) -> dict[str, Any]:
        import google.generativeai as genai
        client = self._load()

        parts: list[Any] = []
        for fp in frame_paths:
            if fp and Path(fp).exists():
                parts.append({"mime_type": "image/jpeg", "data": Path(fp).read_bytes()})
        parts.append(_build_prompt(record))

        response = client.generate_content(parts)
        raw = response.text or ""
        return _parse_label_response(raw)


# ---------------------------------------------------------------------------
# Core pipeline
# ---------------------------------------------------------------------------

def _resolve_frame_paths(
    record: dict[str, Any],
    frames_root: Path | None,
    *,
    videos_root: Path | None = None,
    reconstruction_cache: Path | None = None,
) -> list[Path]:
    """Return [t-2, t-1, t] paths, resolving against frames_root or CWD.

    Falls back to reconstructing frames from a local raw video (via
    ``videos_root``) when the pre-extracted sparse-frame JPEGs aren't present
    — the case for a metadata-only dataset (e.g. downloaded from HuggingFace
    without frame images, for a licensed source dataset like Ego4D whose terms
    don't permit redistributing derived frame crops). See
    ``_reconstruct_frame_paths`` for the reconstruction formula.
    """
    keys = ["frame_t_minus_2_path", "frame_t_minus_1_path", "frame_t_path"]
    paths = []
    for k in keys:
        raw = record.get(k) or ""
        if not raw:
            paths.append(None)
            continue
        p = Path(raw)
        candidates = []
        if frames_root:
            candidates.append(frames_root / p)
        candidates.append(p)                          # relative to CWD
        candidates.append(Path.cwd() / p)            # explicit CWD join
        found = next((c for c in candidates if c.exists()), None)
        paths.append(found)

    if videos_root is not None and any(p is None for p in paths):
        reconstructed = _reconstruct_frame_paths(record, videos_root, reconstruction_cache)
        paths = [existing or reconstructed[i] for i, existing in enumerate(paths)]
    return paths


def _ffmpeg_extract_frame(
    video_path: Path, dest: Path, timestamp_sec: float, *, force: bool = False
) -> Path | None:
    if dest.exists() and not force:
        return dest
    dest.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "ffmpeg", "-hide_banner", "-loglevel", "error",
        "-ss", f"{max(0.0, timestamp_sec):.3f}",
        "-i", str(video_path),
        "-frames:v", "1", "-q:v", "2", "-y", str(dest),
    ]
    try:
        subprocess.run(cmd, check=True)
    except Exception:
        return None
    return dest if dest.exists() else None


def _reconstruct_frame_paths(
    record: dict[str, Any], videos_root: Path, cache_dir: Path | None
) -> list[Path | None]:
    """Reconstruct [t-2, t-1, t] frame images from a local raw video, for a
    metadata-only labels.jsonl (no pre-extracted sparse frames shipped) —
    e.g. an Ego4D-derived dataset, whose license permits sharing our own
    annotations but not redistributing frame crops from the licensed video.

    Needs ``video_id`` (matching Ego4D's own video UID — the raw video is
    expected at ``videos_root/{video_id}.mp4``), ``source_video_start_sec``
    (this clip's offset into that raw video), and ``frame_times_sec`` (local
    offsets within the clip) — all already present in labels.jsonl. The
    absolute timestamp for each tag is simply
    ``source_video_start_sec + frame_times_sec[tag]``.
    """
    video_id = record.get("video_id")
    start = record.get("source_video_start_sec")
    frame_times = record.get("frame_times_sec") or {}
    if not video_id or start is None or not frame_times:
        return [None, None, None]

    video_path = videos_root / f"{video_id}.mp4"
    if not video_path.exists():
        return [None, None, None]

    cache = cache_dir or (videos_root / ".reconstructed_frames")
    cache.mkdir(parents=True, exist_ok=True)
    safe_id = str(record.get("id") or "").replace("/", "_").replace("#", "__")

    results: list[Path | None] = []
    for tag in ("t-2", "t-1", "t"):
        local_sec = frame_times.get(tag)
        if local_sec is None:
            results.append(None)
            continue
        absolute_sec = float(start) + float(local_sec)
        dest = cache / f"{safe_id}__{tag.replace('-', '_')}.jpg"
        results.append(_ffmpeg_extract_frame(video_path, dest, absolute_sec, force=False))
    return results


def _load_existing_ids(path: Path) -> set[str]:
    if not path.exists():
        return set()
    ids: set[str] = set()
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                try:
                    ids.add(json.loads(line)["id"])
                except (json.JSONDecodeError, KeyError):
                    pass
    return ids


def _load_disagreed_rows(path: Path) -> dict[str, dict[str, Any]]:
    """Full prior-crosscheck rows (keyed by id) where the prior judge(s)
    already disagreed with the auto label (``majority_agrees`` is False).

    Used to skip spending a new judge call on these — a disagreement already
    flags the record for human review, so a second judge's opinion doesn't
    change the triage outcome. The full row (not just the id) is kept so it
    can be passed through unchanged into the new output file, keeping the
    output's row count equal to the input's rather than silently dropping
    these records.
    """
    rows: dict[str, dict[str, Any]] = {}
    if not path.exists():
        return rows
    for row in _iter_jsonl(path):
        if row.get("majority_agrees") is False and row.get("id"):
            rows[row["id"]] = row
    return rows


def write_crosscheck_jsonl(
    labels_path: Path,
    out_path: Path,
    judges: list[Any],
    *,
    frames_root: Path | None = None,
    videos_root: Path | None = None,
    only_agreed_in: Path | None = None,
    limit: int | None = None,
    resume: bool = True,
    show_progress: bool = True,
) -> int:
    """Run all judges on each record in labels_path and write agreement stats.

    ``videos_root``, when given, reconstructs a record's sparse frames from a
    local raw video (videos_root/{video_id}.mp4) whenever the pre-extracted
    JPEGs referenced by frames_root aren't found — for a metadata-only
    labels.jsonl (e.g. downloaded from a HuggingFace dataset that ships our
    own annotations but not frame crops derived from a licensed source video
    like Ego4D). See ``_reconstruct_frame_paths``.

    ``only_agreed_in``, when given, points at an existing crosscheck JSONL
    (e.g. from a prior judge). Records already known to disagree there
    (``majority_agrees: false``) are passed through into the output
    unchanged instead of being re-judged here — a disagreement already
    flags the record for human review, so a second judge's opinion doesn't
    change the triage outcome, only costs more API calls. The output still
    gets one row per input record (same total count as an unfiltered run);
    disagreed rows just carry the prior judge's data forward rather than
    being silently dropped.

    Output schema per row:
      id, auto_ground_truth,
      judges: {model_id: {label, object_type_evidence, zone_evidence,
                           relation_graph_evidence, context_change_evidence, agrees}},
      agreement_count, agreement_ratio, majority_label
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    existing_ids = _load_existing_ids(out_path) if resume else set()
    disagreed_rows = _load_disagreed_rows(only_agreed_in) if only_agreed_in else {}

    records = list(_iter_jsonl(labels_path))
    if limit:
        records = records[:limit]

    todo = [r for r in records if r.get("id") not in existing_ids]

    if show_progress:
        try:
            from tqdm.auto import tqdm
            todo = tqdm(todo, total=len(todo), unit="record", desc="vlm-crosscheck")
        except ImportError:
            pass

    n_written = 0
    mode = "a" if resume else "w"
    with out_path.open(mode, encoding="utf-8") as fh:
        for record in todo:
            rid = record.get("id", "")

            if rid in disagreed_rows:
                # Already known to disagree with a prior judge — carry that
                # row forward unchanged rather than spending a new judge
                # call on it, while still keeping the output complete.
                fh.write(json.dumps(disagreed_rows[rid], ensure_ascii=False) + "\n")
                fh.flush()
                n_written += 1
                continue

            auto_gt = record.get("auto_ground_truth") or record.get("auto_label") or ""
            ref_bbox = (record.get("object") or {}).get("bbox") or {}
            temporal_objects = record.get("temporal_target_objects") or {}

            # Frame t always gets ref_bbox (the verified anchor). t-1/t-2 get
            # their own genuinely-tracked box (from --sam2-track) when one
            # exists for that frame; otherwise they're shown unboxed rather
            # than falling back to reusing t's box, which used to draw a
            # stale, unrelated-looking box whenever no real tracked position
            # existed for that frame — which was most of the time.
            raw_paths = _resolve_frame_paths(
                record, frames_root,
                videos_root=videos_root,
                reconstruction_cache=out_path.parent / f"{out_path.stem}_reconstructed_frames",
            )
            with tempfile.TemporaryDirectory() as tmp:
                tmp_path = Path(tmp)
                annotated_paths: list[Path | None] = []
                for tag, src in zip(("t-2", "t-1", "t"), raw_paths):
                    frame_bbox = ref_bbox if tag == "t" else (temporal_objects.get(tag) or {}).get("bbox")
                    if src and src.exists() and frame_bbox:
                        dst = tmp_path / f"frame_{tag.replace('-', '_')}_bbox.jpg"
                        _draw_bbox_on_frame(src, dst, frame_bbox)
                        annotated_paths.append(dst)
                    else:
                        annotated_paths.append(src)  # no genuine box for this frame: shown unboxed

                frame_paths = [p for p in annotated_paths if p and Path(p).exists()]

                judge_results: dict[str, dict] = {}
                for judge in judges:
                    try:
                        result = judge.judge(frame_paths, record)
                    except Exception as exc:
                        result = {"label": "ERROR", **{f: "" for f in _EVIDENCE_FIELDS}, "error": str(exc)[:200]}
                    result["agrees"] = (result.get("label") == auto_gt)
                    judge_results[judge.model_id] = result

            labels_predicted = [v["label"] for v in judge_results.values() if v["label"] in VALID_LABELS]
            agreement_count = sum(1 for v in judge_results.values() if v.get("agrees"))
            majority_label = Counter(labels_predicted).most_common(1)[0][0] if labels_predicted else "UNKNOWN"

            row = {
                "id": rid,
                "auto_ground_truth": auto_gt,
                "judges": judge_results,
                "agreement_count": agreement_count,
                "agreement_ratio": round(agreement_count / max(1, len(judge_results)), 4),
                "majority_label": majority_label,
                "majority_agrees": majority_label == auto_gt,
            }
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")
            fh.flush()
            n_written += 1

    return n_written


def merge_crosscheck_jsonl(paths: list[Path], out_path: Path) -> int:
    """Merge two or more crosscheck JSONL files (e.g. separate per-judge runs
    from ``--only-agreed-in``) into one file with every judge's result per id.

    Rows are combined by ``id``; each input's ``judges`` dict is unioned
    together (a later path's judge overwrites an earlier one only if they
    share the same model_id key), and agreement_count/ratio/majority_label/
    majority_agrees are recomputed over the combined judge set. A row missing
    from some inputs but present in others is still included, using
    whichever ones have it.
    """
    rows_by_id: dict[str, dict[str, Any]] = {}
    order: list[str] = []
    for path in paths:
        for row in _iter_jsonl(path):
            rid = row.get("id")
            if not rid:
                continue
            if rid not in rows_by_id:
                order.append(rid)
                rows_by_id[rid] = {"id": rid, "auto_ground_truth": row.get("auto_ground_truth", ""), "judges": {}}
            rows_by_id[rid]["judges"].update(row.get("judges") or {})
            if not rows_by_id[rid]["auto_ground_truth"]:
                rows_by_id[rid]["auto_ground_truth"] = row.get("auto_ground_truth", "")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    n_written = 0
    with out_path.open("w", encoding="utf-8") as fh:
        for rid in order:
            merged = rows_by_id[rid]
            judges = merged["judges"]
            auto_gt = merged["auto_ground_truth"]
            labels_predicted = [v["label"] for v in judges.values() if v.get("label") in VALID_LABELS]
            agreement_count = sum(1 for v in judges.values() if v.get("agrees"))
            majority_label = Counter(labels_predicted).most_common(1)[0][0] if labels_predicted else "UNKNOWN"
            row = {
                "id": rid,
                "auto_ground_truth": auto_gt,
                "judges": judges,
                "agreement_count": agreement_count,
                "agreement_ratio": round(agreement_count / max(1, len(judges)), 4),
                "majority_label": majority_label,
                "majority_agrees": majority_label == auto_gt,
            }
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")
            n_written += 1
    return n_written
